version: "3"
services:
  # The Application
  fovina_app_web_qlqt:
    container_name: fovina_app_web_qlqt
    build:
      context: ./
      dockerfile: web.dockerfile
    restart: always
    networks:
      - traefik_traefik
    working_dir: /var/www
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fovina_app_web_qlqt.entrypoints=http"
      - "traefik.http.routers.fovina_app_web_qlqt.rule=Host(`qlqt.fovina.bfd.vn`)"
      - "traefik.docker.network=traefik_traefik"
      - "traefik.http.services.fovina_app_web_qlqt.loadbalancer.server.port=80"

      - "traefik.http.middlewares.fovina_app_web_qlqt-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.fovina_app_web_qlqt-https-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.fovina_app_web_qlqt.middlewares=fovina_app_web_qlqt-https-redirect"
      - "traefik.http.routers.fovina_app_web_qlqt-secure.rule=Host(`qlqt.fovina.bfd.vn`)"
      - "traefik.http.routers.fovina_app_web_qlqt-secure.tls=true"
      - "traefik.http.routers.fovina_app_web_qlqt-secure.tls.certresolver=http"
      - "traefik.http.routers.fovina_app_web_qlqt-secure.entrypoints=https"
      - "traefik.http.routers.fovina_app_web_qlqt-secure.service=fovina_app_web_qlqt"

networks:
  traefik_traefik:
    external: true
